export const welcomeMail = {
    subject: 'Velkommen til kompetansekartlegging!',
    body: 'Hei'
    + '<br><br>'
    + 'I denne e-posten kommer både informasjon om kompetansekartleggingen og lenke til utfylling. '
    + '<br><br>'
    + '<u><strong>Hvorfor og hvordan vi skal gjennomføre kompetansekartlegging</u></strong>'
    + '<br>'
    + 'Kompetansekartleggingen skal gi oss en helhetlig digital oversikt over kompetansen til ansatte i VTFK og bidra til arbeidet med å sikre at begge de nye fylkeskommunene har tilstrekkelig kompetanse til å bemanne alle funksjoner.'
    + '<br>'
    + 'Kompetansekartleggingen skal foregå ved at både ledere og medarbeidere fyller ut den digitale kompetansemodulen. Den er sendt til lederne først og sendes nå til alle medarbeidere. '
    + '<br>'
    + 'Merk at kompetansekartleggingen ikke er innplasseringen. I løpet av våren 2023 vil din leder gjennomføre en kartleggingssamtale med deg. Det du svarer i kompetansekartleggingen vil være en del av kartleggingssamtalen. Mer informasjon om personalløpet, kartleggingssamtaler og innplassering vil bli gitt.'
    + '<br><br>'
    + '<u><strong>Hvem skal svare på kompetansekartleggingen</u></strong>'
    + '<br>'
    + 'De som skal gjennomføre kompetansekartleggingen er alle faste ansatte i fylkesadministrasjonen inkludert OT og PPT, samt midlertidig ansatte i fylkesadministrasjonen inkludert OT og PPT med kontrakt utover 01.01.24. '
    + '<br>'
    + "Ansatte i virksomhetene, ansatte som har sluttet til 1.1.24, midlertidige ansatte som ikke skal være med videre etter 1.1.24, vikarer, lærlinger og trainee'er eller innleide konsulenter skal ikke besvare kartleggingen. <a href='https://vtfk.sharepoint.com/sites/innsida-varorganisasjon/sitepages/NyefylkerHR.aspx?xsdata=MDN8MDF8fDA0NmJmZTkyZGY3MDQ3ZThhMTgyNThjYmZiZDU4OGEwfDA4ZjM4MTNjOWYyOTQ4MmY5YWVjMTZlZjdjYmY0NzdhfDB8MHw2Mzc4NDc0MDc2MDYyMjc3NzZ8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT0%3D&sdata=SzVsd29NS0cxT3MvWDYyUHEzV2tYSHFzTFJhcTdkd1JoWSsvK041eENBND0%3D&ovuser=08f3813c-9f29-482f-9aec-16ef7cbf477a%2ccharlotte.erikstad%40vtfk.no&OR=Teams-HL&CT=1649143975552&params=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjAzMDcwMTYxMCJ9'>Du finner mer informasjon her.</a>"
    + '<br><br>'
    + '<u><strong>Hvor finner du kompetansemodulen?</u></strong>'
    + '<br>'
    + 'Du bruker lenken her for å komme til kompetansemodulen: <a href="https://kompetanse.vtfk.no">Kompetanse (vtfk.no)</a>'
    + '<br>'
    + 'Frist for utfylling er 16.desember.'
    + '<br><br>'
    + '<u><strong>Personvern</u></strong>'
    + '<br>'
    + 'Kartleggingen er bygd opp etter reglene i personvernlovgivningen. Du finner vår personvernerklæring på Innsida og i modulen.'
    + '<br>'
    + 'I personvernerklæringen finner du informasjon om dine rettigheter og formålet med innsamlingen.'
    + '<br><br>'
    + '<u><strong>Vil du lese mer?</u></strong>'
    + '<br>'
    + 'Du finner mer informasjon på innsida under <a href="https://vtfk.sharepoint.com/sites/innsida-varorganisasjon/sitepages/NyefylkerHR.aspx?xsdata=MDN8MDF8fDA0NmJmZTkyZGY3MDQ3ZThhMTgyNThjYmZiZDU4OGEwfDA4ZjM4MTNjOWYyOTQ4MmY5YWVjMTZlZjdjYmY0NzdhfDB8MHw2Mzc4NDc0MDc2MDYyMjc3NzZ8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT0%3D&sdata=SzVsd29NS0cxT3MvWDYyUHEzV2tYSHFzTFJhcTdkd1JoWSsvK041eENBND0%3D&ovuser=08f3813c-9f29-482f-9aec-16ef7cbf477a%2ccharlotte.erikstad%40vtfk.no&OR=Teams-HL&CT=1649143975552&params=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjAzMDcwMTYxMCJ9">«Vi bygger nye fylkeskommuner - Aktuelt nå: Kompetansekartlegging».</a> Det er også informasjon inne i selve kompetansemodulen under fanen «Hjelp».'
    + '<br><br>'
    + '<u><strong>Har du spørsmål?</u></strong>'
    + '<br>'
    + 'Dersom du har spørsmål eller noe er uklart kan du ta kontakt med din nærmeste leder eller delprosjektHR@vtfk.no'
}

export const remindMail = {
    subject: 'Påminnelse om kompetansekartlegging',
    body: 'Hei,'
    + '<br><br>'
    + 'I dag går fristen for å svare på kompetansekartleggingen ut for medarbeidere i fylkesadministrasjonen. Vi kan ikke se at du har lagt inn informasjon i modulen ennå eller mangler å fylle ut deler av kartleggingen. Dette er en vennlig påminnelse om å fullføre kompetansekartleggingen.'
    + '<br><br>'
    + '<strong>Her finner dere lenken til kompetansemodulen:</strong> <a href="https://kompetanse.vtfk.no">Kompetanse (vtfk.no)</a>'
    + '<br><br>'
    + 'De som skal gjennomføre kompetansekartleggingen er alle faste ansatte i fylkesadministrasjonen inkludert OT og PPT, samt midlertidig ansatte i fylkesadministrasjonen inkludert OT og PPT med kontrakt <strong>utover 01.01.24.</strong>'
    + '<br><br>'
    + "Ansatte i virksomhetene, ansatte som har sluttet til 1.1.24, midlertidige ansatte som ikke skal være med videre etter 1.1.24, vikarer, lærlinger og trainee'er eller innleide konsulenter skal ikke besvare kartleggingen. Du finner mer informasjon på Innsida under <a href='https://vtfk.sharepoint.com/sites/innsida-varorganisasjon/sitepages/NyefylkerHR.aspx?xsdata=MDN8MDF8fDA0NmJmZTkyZGY3MDQ3ZThhMTgyNThjYmZiZDU4OGEwfDA4ZjM4MTNjOWYyOTQ4MmY5YWVjMTZlZjdjYmY0NzdhfDB8MHw2Mzc4NDc0MDc2MDYyMjc3NzZ8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT0%3D&sdata=SzVsd29NS0cxT3MvWDYyUHEzV2tYSHFzTFJhcTdkd1JoWSsvK041eENBND0%3D&ovuser=08f3813c-9f29-482f-9aec-16ef7cbf477a%2ccharlotte.erikstad%40vtfk.no&OR=Teams-HL&CT=1649143975552&params=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjAzMDcwMTYxMCJ9'>«Vi bygger nye fylkeskommuner - Aktuelt nå: Kompetansekartlegging».</a>"
    + '<br><br><br>'
    + '<strong>Har du spørsmål?</strong>'
    + '<br>'
    + 'Dersom du har spørsmål eller noe er uklart kan du ta kontakt med din nærmeste leder.'
    + '<br>'
    + "Du finner også informasjon på Innsida under <a href='https://vtfk.sharepoint.com/sites/innsida-varorganisasjon/sitepages/NyefylkerHR.aspx?xsdata=MDN8MDF8fDA0NmJmZTkyZGY3MDQ3ZThhMTgyNThjYmZiZDU4OGEwfDA4ZjM4MTNjOWYyOTQ4MmY5YWVjMTZlZjdjYmY0NzdhfDB8MHw2Mzc4NDc0MDc2MDYyMjc3NzZ8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT0%3D&sdata=SzVsd29NS0cxT3MvWDYyUHEzV2tYSHFzTFJhcTdkd1JoWSsvK041eENBND0%3D&ovuser=08f3813c-9f29-482f-9aec-16ef7cbf477a%2ccharlotte.erikstad%40vtfk.no&OR=Teams-HL&CT=1649143975552&params=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjAzMDcwMTYxMCJ9'>«Vi bygger nye fylkeskommuner - Aktuelt nå: Kompetansekartlegging».</a> 🎅"
}