on:
  release:
    types: [published]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: curl -X POST -d {} https://api.vercel.com/v1/integrations/deploy/prj_VYv4hi8PNPwVMJKQTas5mkbMYrR3/HPE6pvYBSV
